[project]
name = "mlebench-inspect"
version = "0.1.0"
description = ""
authors = []
dependencies = []
requires-python = "==3.11.*"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 